Table subscriptions {
  user_id uuid [primary key]
  followed_user_id uuid [primary key]
  created_at timestamp
}

Table users {
  id uuid [primary key]
  username varchar
  email varchar
  first_name varchar
  last_name varchar
  description varchar
  created_at timestamp
  avatar_id uuid
}

Table posts {
  id uuid [primary key]
  title varchar
  text text [note: 'Content of the post']
  user_id uuid
  location_id uuid
  rate integer
  created_at timestamp
  updated_at timestamp
  likes int
}

Table photos {
  id uuid [primary key]
  post_id uuid
  user_id uuid
  s3_key varchar
  created_at timestamp
}

Table comments {
  id uuid
  post_id uuid
  text text
  created_at timestamp
}

Table likes {
  post_id uuid [primary key]
  user_id uuid [primary key]
}

Table locations {
  id uuid [primary key]
  locality_id uuid
  name varchar
  point point
}

// This table might look different. It is for backoffice usage.
Table localities {
  id uuid [primary key]
  country varchar
  province varchar
  city varchar
}




Ref: "locations"."id" < "posts"."location_id"

Ref: "photos"."id" < "users"."avatar_id"

Ref: "posts"."id" < "comments"."id"

Ref: "localities"."id" < "locations"."locality_id"

Ref: "posts"."id" < "likes"."post_id"

Ref: "users"."id" < "likes"."user_id"

Ref: "users"."id" < "posts"."user_id"

Ref: "users"."id" < "subscriptions"."user_id"

Ref: "users"."id" < "subscriptions"."followed_user_id"

Ref: "posts"."id" < "photos"."post_id"